version: '3'
services:
  app:
    container_name: gpw-app
    restart: always
    image: amazoncorretto:19-alpine-jdk
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    networks:
      - gpw-network
    volumes:
      - ./target/gpw-app.jar:/gpw-app.jar
    entrypoint: java -jar /gpw-app.jar

networks:
  gpw-network: