version: '3'
services:
  app:
    container_name: gpw-app
    restart: always
    image: amazoncorretto:19-alpine-jdk
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      APP_TEMP_DIR: /app-data
      spring_profiles_active: prod
    networks:
      - gpw-network
    volumes:
      - ./target/gpw-app.jar:/gpw-app.jar
      - ./docker-volumes/app-data:/app-data
    entrypoint: java -jar /gpw-app.jar

networks:
  gpw-network: