version: '3'
services:
  mysql:
    container_name: gpw-mysql
    restart: always
    image: mysql:5.7
    # no problem with login by user nad password (plain text)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: gpw-mysql-root-password-123234!
      MYSQL_USER: gpw
      MYSQL_PASSWORD: gpw-password-213!
      MYSQL_DATABASE: gpw-db
    ports:
      - "3309:3306"
    networks:
      - gpw-network
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql

networks:
  gpw-network:
